
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTAND LPAREN NOT OR QUOTED_STRING RPAREN WORDquery : expressionexpression : expression AND expression\n    | expression OR expressionexpression : NOT expressionexpression : LPAREN expression RPARENexpression : term_listterm_list : termterm_list : term_list termterm : WORDterm : QUOTED_STRING'
    
_lr_action_items = {'NOT':([0,3,4,9,10,],[3,3,3,3,3,]),'LPAREN':([0,3,4,9,10,],[4,4,4,4,4,]),'WORD':([0,3,4,5,6,7,8,9,10,13,],[7,7,7,7,-7,-9,-10,7,7,-8,]),'QUOTED_STRING':([0,3,4,5,6,7,8,9,10,13,],[8,8,8,8,-7,-9,-10,8,8,-8,]),'$end':([1,2,5,6,7,8,11,13,14,15,16,],[0,-1,-6,-7,-9,-10,-4,-8,-2,-3,-5,]),'AND':([2,5,6,7,8,11,12,13,14,15,16,],[9,-6,-7,-9,-10,-4,9,-8,-2,9,-5,]),'OR':([2,5,6,7,8,11,12,13,14,15,16,],[10,-6,-7,-9,-10,-4,10,-8,-2,-3,-5,]),'RPAREN':([5,6,7,8,11,12,13,14,15,16,],[-6,-7,-9,-10,-4,16,-8,-2,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'expression':([0,3,4,9,10,],[2,11,12,14,15,]),'term_list':([0,3,4,9,10,],[5,5,5,5,5,]),'term':([0,3,4,5,9,10,],[6,6,6,13,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> expression','query',1,'p_query','boolean_query_parser.py',177),
  ('expression -> expression AND expression','expression',3,'p_expression_binop','boolean_query_parser.py',182),
  ('expression -> expression OR expression','expression',3,'p_expression_binop','boolean_query_parser.py',183),
  ('expression -> NOT expression','expression',2,'p_expression_not','boolean_query_parser.py',188),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','boolean_query_parser.py',193),
  ('expression -> term_list','expression',1,'p_expression_term_list','boolean_query_parser.py',198),
  ('term_list -> term','term_list',1,'p_term_list_single','boolean_query_parser.py',203),
  ('term_list -> term_list term','term_list',2,'p_term_list_multiple','boolean_query_parser.py',211),
  ('term -> WORD','term',1,'p_term_word','boolean_query_parser.py',220),
  ('term -> QUOTED_STRING','term',1,'p_term_quoted','boolean_query_parser.py',225),
]
